name: Build and deploy GradeX Frontend to Azure

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build GradeX frontend
        run: npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradex-dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: gradex-dist
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_23CAB314178C412993E1247DFAACA9A6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AC7C915F314A49BCA9842FA13BA103FE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_046EC26F405F4AC085DCA2472B99080F }}

      - name: Deploy GradeX Frontend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gradex-front'
          slot-name: 'Production'
          package: .